export const SOCIETY_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
}

export const FLAT_STATUS = {
  VACANT: 'VACANT',
  OCCUPIED: 'OCCUPIED',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
}

export const FLAT_TYPES = {
  STUDIO: 'STUDIO',
  ONE_BHK: '1BHK',
  TWO_BHK: '2BHK',
  THREE_BHK: '3BHK',
  FOUR_BHK: '4BHK',
  PENTHOUSE: 'PENTHOUSE',
  SHOP: 'SHOP',
  OTHER: 'OTHER',
}

export const OWNERSHIP_TYPE = {
  OWNER: 'OWNER',
  TENANT: 'TENANT',
  FAMILY: 'FAMILY',
}

export const MEMBER_RELATION = {
  SELF: 'SELF',
  SPOUSE: 'SPOUSE',
  CHILD: 'CHILD',
  PARENT: 'PARENT',
  SIBLING: 'SIBLING',
  OTHER: 'OTHER',
}

export const VISITOR_STATUS = {
  EXPECTED: 'EXPECTED',
  CHECKED_IN: 'CHECKED_IN',
  CHECKED_OUT: 'CHECKED_OUT',
  DENIED: 'DENIED',
  CANCELLED: 'CANCELLED',
}

export const COMPLAINT_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED',
}

export const COMPLAINT_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
}

export const MAINTENANCE_STATUS = {
  OPEN: 'OPEN',
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
}

export const INVOICE_STATUS = {
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED',
}

export const INVOICE_TYPE = {
  MAINTENANCE: 'MAINTENANCE',
  PARKING: 'PARKING',
  UTILITY: 'UTILITY',
  PENALTY: 'PENALTY',
  EVENT: 'EVENT',
  OTHER: 'OTHER',
}

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
}

export const PAYMENT_METHOD = {
  CASH: 'CASH',
  UPI: 'UPI',
  CARD: 'CARD',
  NET_BANKING: 'NET_BANKING',
  CHEQUE: 'CHEQUE',
  OTHER: 'OTHER',
}

export const EVENT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
}

export const DOCUMENT_VISIBILITY = {
  SOCIETY: 'SOCIETY',
  WING: 'WING',
  FLAT: 'FLAT',
  PRIVATE: 'PRIVATE',
}

export const PARKING_TYPE = {
  OPEN: 'OPEN',
  COVERED: 'COVERED',
  BASEMENT: 'BASEMENT',
}

export const PARKING_STATUS = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  RESERVED: 'RESERVED',
  BLOCKED: 'BLOCKED',
}

export const VEHICLE_TYPE = {
  TWO_WHEELER: 'TWO_WHEELER',
  FOUR_WHEELER: 'FOUR_WHEELER',
  OTHER: 'OTHER',
}

export const STAFF_DEPARTMENT = {
  ADMIN: 'ADMIN',
  MAINTENANCE: 'MAINTENANCE',
  HOUSEKEEPING: 'HOUSEKEEPING',
  SECURITY: 'SECURITY',
  ACCOUNTING: 'ACCOUNTING',
  OTHER: 'OTHER',
}

export const GUARD_SHIFT = {
  MORNING: 'MORNING',
  EVENING: 'EVENING',
  NIGHT: 'NIGHT',
  ROTATIONAL: 'ROTATIONAL',
}

export const EMERGENCY_CONTACT_TYPE = {
  POLICE: 'POLICE',
  FIRE: 'FIRE',
  AMBULANCE: 'AMBULANCE',
  HOSPITAL: 'HOSPITAL',
  MANAGEMENT: 'MANAGEMENT',
  CUSTOM: 'CUSTOM',
}

export const NOTIFICATION_TYPE = {
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
  COMPLAINT: 'COMPLAINT',
  PAYMENT: 'PAYMENT',
  EVENT: 'EVENT',
  VISITOR: 'VISITOR',
  SYSTEM: 'SYSTEM',
}

export const SUPPORT_TICKET_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_ON_USER: 'WAITING_ON_USER',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
}

export const SUPPORT_TICKET_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
}

export const ACTIVITY_ACTION = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  STATUS_CHANGE: 'STATUS_CHANGE',
  OTHER: 'OTHER',
}
